spring:
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/recipedb #change to ip from localhost so container doesn't get confused
    username: backend
    password: backend
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create
  kafka:
    consumer:
      group-id: recipe-application

server:
  servlet:
    context-path: /v1

auth:
  service:
    url: http://localhost:8181 #change to ip from localhost so container doesn't get confused