services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  #mongoDB
  mongodb:
    image: mongo:7.0.5
    container_name: cookbook-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoSA
      MONGO_INITDB_ROOT_PASSWORD: mongoSA
      MONGO_INITDB_DATABASE: cookbookdb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  #Redis
  redis:
    container_name: redis
    image: "redis:latest"
    ports:
      - "6379:6379"

  #AuthService
  authenticationservice:
    build: ./AuthenticationService
    container_name: authenticationservice
    expose:
      - "8181"
    environment:
      SPRING_PROFILES_ACTIVE: 'production'

  #RecipeApplication
  recipeservice:
    build: ./RecipeApplication
    container_name: recipeapplication
    depends_on:
      - broker
    expose:
      - "8282"
    environment:
      SPRING_PROFILES_ACTIVE: 'production'
      DEVTIRO_KAFKA_TOPIC: 'recipe.published'
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 'broker:29092'

  #CookBookApplication
  cookbookapplication:
    build: ./CookBookApplication
    container_name: cookbookapplication
    depends_on:
      - broker
      - mongodb
    expose:
      - "8383"
    environment:
      SPRING_PROFILES_ACTIVE: 'production'
      DEVITRO_KAFKA_CLONE_TOPIC: 'recipe.clone'
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 'broker:29092'
      MONGODB_USERNAME: mongoSA
      MONGODB_PASSWORD: mongoSA

  #GatewayService
  gatewayservice:
    build: ./Gateway
    container_name: gateway
    depends_on:
      - redis
      - authenticationservice
      - recipeservice
      - cookbookapplication
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: 'production'
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

volumes:
  mongo-data:
    driver: local
