spring:
  application:
    name: Gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      globalcors:
        cors-configurations:
          '[/**]': # Apply to all routes
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true