logging:
  level:
    org.springframework.cloud.gateway.filter.ratelimit: DEBUG

spring:
  application:
    name: Gateway
  redis:
    host: ${SPRING_REDIS_HOST:redis}
    port: ${SPRING_REDIS_PORT:6379}
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      globalcors:
        cors-configurations:
          '[/**]': # Apply to all routes
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

auth:
  service:
    url: http://authenticationservice:8080 #change to ip from localhost so container doesn't get confused