spring:
  data:
    mongodb:
        uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017/cookbookdb?authSource=admin
  kafka:
    consumer:
      group-id: cookbook-application

server:
  servlet:
    context-path: /v1/cb
